# Generated by Django 5.0.6 on 2024-09-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_carmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=500)),
                ("year", models.PositiveIntegerField()),
                ("model", models.CharField(max_length=500)),
                ("trim", models.CharField(max_length=500)),
                ("color", models.CharField(max_length=500)),
            ],
            options={
                "unique_together": {("make", "year", "model", "trim", "color")},
            },
        ),
        migrations.DeleteModel(
            name="CarModel",
        ),
    ]
