# Generated by Django 5.0.6 on 2024-08-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="admin_ready_tocheck",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="business_name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_approved",
        ),
    ]
